
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS FUNCTION IDENTIFIER LBRACKET LPAREN NUMBER PLUS RBRACKET RPARENprogram : statement\n            | expression\n            | function_defexpression : NUMBERexpression : IDENTIFIERexpression : expression PLUS expressionfunction_def : FUNCTION IDENTIFIER LBRACKET expression RBRACKETstatement : IDENTIFIER EQUALS expression'
    
_lr_action_items = {'IDENTIFIER':([0,7,8,9,14,],[5,10,12,12,12,]),'NUMBER':([0,8,9,14,],[6,6,6,6,]),'FUNCTION':([0,],[7,]),'$end':([1,2,3,4,5,6,11,12,13,16,],[0,-1,-2,-3,-5,-4,-6,-5,-8,-7,]),'PLUS':([3,5,6,11,12,13,15,],[8,-5,-4,8,-5,8,8,]),'EQUALS':([5,],[9,]),'RBRACKET':([6,11,12,15,],[-4,-6,-5,16,]),'LBRACKET':([10,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,],[2,]),'expression':([0,8,9,14,],[3,11,13,15,]),'function_def':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program','main.py',63),
  ('program -> expression','program',1,'p_program','main.py',64),
  ('program -> function_def','program',1,'p_program','main.py',65),
  ('expression -> NUMBER','expression',1,'p_expression_number','main.py',68),
  ('expression -> IDENTIFIER','expression',1,'p_expression_identifier','main.py',71),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','main.py',74),
  ('function_def -> FUNCTION IDENTIFIER LBRACKET expression RBRACKET','function_def',5,'p_function_def','main.py',77),
  ('statement -> IDENTIFIER EQUALS expression','statement',3,'p_statement_assing','main.py',81),
]
